import type { AssignmentNotification, DeliveryThread, Parcel, Trip, VerificationCase } from '../../src/types';

export const seedParcels: Parcel[] = [
  {
    id: 'parcel-001',
    senderName: 'Jaydeep Kumar',
    parcelCategory: 'Documents',
    weight: 0.6,
    dimensions: 'Small',
    declaredValue: 'Up to Rs 500',
    pickupAddress: 'Connaught Place, New Delhi',
    dropoffAddress: 'Gomti Nagar, Lucknow',
    reward: 420,
    status: 'matched',
    fromCity: 'Delhi',
    toCity: 'Lucknow',
    pickupDate: '2026-03-25',
    createdAt: '2026-03-22T09:00:00.000Z',
    description: 'Urgent paperwork for same-day handoff.',
    photoNames: ['invoice-front.jpg'],
    travelerName: 'Amit R.',
    otpCode: '1934',
  },
  {
    id: 'parcel-002',
    senderName: 'Priya Malhotra',
    parcelCategory: 'Electronics',
    weight: 1.8,
    dimensions: 'Medium',
    declaredValue: 'Rs 2,000 - Rs 5,000',
    pickupAddress: 'Noida Sector 62, Noida',
    dropoffAddress: 'Indiranagar, Bangalore',
    reward: 1300,
    status: 'in_transit',
    fromCity: 'Noida',
    toCity: 'Bangalore',
    pickupDate: '2026-03-24',
    createdAt: '2026-03-21T15:30:00.000Z',
    description: 'Compact audio device in original packaging.',
    photoNames: ['device-box.png', 'seal-check.png'],
    travelerName: 'Rahul S.',
    otpCode: '4721',
  },
  {
    id: 'parcel-003',
    senderName: 'Nikita Shah',
    parcelCategory: 'Clothing',
    weight: 2.4,
    dimensions: 'Large',
    declaredValue: 'Rs 500 - Rs 2,000',
    pickupAddress: 'Vastrapur, Ahmedabad',
    dropoffAddress: 'Kothrud, Pune',
    reward: 780,
    status: 'delivered',
    fromCity: 'Ahmedabad',
    toCity: 'Pune',
    pickupDate: '2026-03-18',
    createdAt: '2026-03-17T11:15:00.000Z',
    description: 'Folded apparel bag for a wedding event.',
    photoNames: ['garment-bag.jpg'],
    travelerName: 'Sonal P.',
    otpCode: '5520',
  },
  {
    id: 'parcel-004',
    senderName: 'Rohit Verma',
    parcelCategory: 'Books',
    weight: 3.2,
    dimensions: 'Medium',
    declaredValue: 'Rs 500 - Rs 2,000',
    pickupAddress: 'Karol Bagh, Delhi',
    dropoffAddress: 'Andheri East, Mumbai',
    reward: 950,
    status: 'posted',
    fromCity: 'Delhi',
    toCity: 'Mumbai',
    pickupDate: '2026-03-26',
    createdAt: '2026-03-24T10:05:00.000Z',
    description: 'Exam prep books packed in a sealed carton.',
    photoNames: ['books-carton.jpg'],
    otpCode: '6815',
  },
];

export const seedTrips: Trip[] = [
  {
    id: 'trip-001',
    travelerName: 'Amit R.',
    fromCity: 'Noida',
    toCity: 'Kanpur',
    date: '2026-03-25',
    mode: 'car',
    availableSpace: 12,
    status: 'active',
    isVerified: true,
    trustScore: 92,
  },
  {
    id: 'trip-002',
    travelerName: 'Suresh K.',
    fromCity: 'Delhi',
    toCity: 'Mumbai',
    date: '2026-03-26',
    mode: 'flight',
    availableSpace: 7,
    status: 'active',
    isVerified: false,
    trustScore: 71,
  },
  {
    id: 'trip-003',
    travelerName: 'Priya M.',
    fromCity: 'Bangalore',
    toCity: 'Chennai',
    date: '2026-03-27',
    mode: 'train',
    availableSpace: 10,
    status: 'active',
    isVerified: true,
    trustScore: 95,
  },
  {
    id: 'trip-004',
    travelerName: 'Aditya N.',
    fromCity: 'Jaipur',
    toCity: 'Delhi',
    date: '2026-03-28',
    mode: 'bus',
    availableSpace: 8,
    status: 'active',
    isVerified: true,
    trustScore: 88,
  },
];

export const seedVerificationCases: VerificationCase[] = [
  {
    id: 'verify-001',
    travelerName: 'Amit R.',
    route: 'Noida -> Kanpur',
    idType: 'Aadhaar Card',
    submittedAt: '2026-03-23T13:15:00.000Z',
    city: 'Greater Noida',
    status: 'pending',
  },
  {
    id: 'verify-002',
    travelerName: 'Suresh K.',
    route: 'Delhi -> Mumbai',
    idType: 'Passport',
    submittedAt: '2026-03-23T12:45:00.000Z',
    city: 'New Delhi',
    status: 'pending',
  },
  {
    id: 'verify-003',
    travelerName: 'Priya M.',
    route: 'Bangalore -> Chennai',
    idType: 'Driving License',
    submittedAt: '2026-03-23T11:20:00.000Z',
    city: 'Bangalore',
    status: 'pending',
  },
];

export const seedDeliveryThreads: DeliveryThread[] = [
  {
    id: 'thread-001',
    parcelId: 'parcel-001',
    routeId: 'parcel-route-001',
    travelerName: 'Amit R.',
    userName: 'Jaydeep Kumar',
    fromCity: 'Delhi',
    toCity: 'Lucknow',
    securityGroupTag: 'SG-DEL-LKO-41',
    pickupSummary: 'Traveler will collect from Gate 3, Rajiv Chowk Metro, at 7:30 PM after ID and tag verification.',
    dropoffSummary: 'Final drop point will be confirmed in Lucknow chat near Patrakarpuram Chauraha before handoff.',
    currentLocation: 'Yamuna Expressway checkpoint',
    lastUpdated: '2026-03-24T18:40:00.000Z',
    progress: 46,
    responsibilitySummary: 'Documents stay sealed by the user, and the traveler is responsible only for sealed handoff and OTP completion.',
    isHighValue: false,
    chat: [
      {
        id: 'thread-001-message-001',
        actor: 'system',
        text: 'Security group tag matched for Jaydeep Kumar and Amit R.',
        sentAt: '2026-03-24T16:30:00.000Z',
      },
      {
        id: 'thread-001-message-002',
        actor: 'traveler',
        text: 'Pickup point is Gate 3, Rajiv Chowk Metro, 7:30 PM. Please keep the envelope sealed.',
        sentAt: '2026-03-24T16:34:00.000Z',
      },
      {
        id: 'thread-001-message-003',
        actor: 'user',
        text: 'Confirmed. I will share the receiver contact once you cross Kanpur.',
        sentAt: '2026-03-24T16:38:00.000Z',
      },
      {
        id: 'thread-001-message-004',
        actor: 'traveler',
        text: 'Drop point in Lucknow will be sent here after I reach Gomti Nagar side.',
        sentAt: '2026-03-24T18:12:00.000Z',
      },
    ],
    checkpoints: [
      {
        id: 'thread-001-checkpoint-001',
        label: 'Pickup confirmed',
        location: 'Rajiv Chowk Metro, Delhi',
        etaLabel: 'Completed at 7:35 PM',
        status: 'completed',
      },
      {
        id: 'thread-001-checkpoint-002',
        label: 'Mid-route scan',
        location: 'Yamuna Expressway checkpoint',
        etaLabel: 'Live now',
        status: 'active',
      },
      {
        id: 'thread-001-checkpoint-003',
        label: 'Receiver handoff',
        location: 'Gomti Nagar, Lucknow',
        etaLabel: 'ETA tomorrow 8:30 AM',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'thread-002',
    parcelId: 'parcel-002',
    routeId: 'parcel-route-002',
    travelerName: 'Rahul S.',
    userName: 'Priya Malhotra',
    fromCity: 'Noida',
    toCity: 'Bangalore',
    securityGroupTag: 'SG-NOI-BLR-88',
    pickupSummary: 'Traveler collected the sealed electronics box from Noida Sector 62 after matching the tag and OTP starter code.',
    dropoffSummary: 'Traveler shared the Bengaluru airport pickup lounge and will post the exact drop pin in chat 30 minutes before arrival.',
    currentLocation: 'Kempegowda Airport transfer desk',
    lastUpdated: '2026-03-24T19:10:00.000Z',
    progress: 79,
    responsibilitySummary: 'This high-value item requires seal-photo proof, no unboxing in transit, and joint OTP confirmation at drop.',
    isHighValue: true,
    chat: [
      {
        id: 'thread-002-message-001',
        actor: 'system',
        text: 'Security group tag matched for Priya Malhotra and Rahul S.',
        sentAt: '2026-03-24T08:15:00.000Z',
      },
      {
        id: 'thread-002-message-002',
        actor: 'traveler',
        text: 'Pickup done at Noida Sector 62. Seal photos uploaded and package is in cabin baggage.',
        sentAt: '2026-03-24T08:22:00.000Z',
      },
      {
        id: 'thread-002-message-003',
        actor: 'user',
        text: 'Please share the Bengaluru drop point here only after you land.',
        sentAt: '2026-03-24T08:24:00.000Z',
      },
      {
        id: 'thread-002-message-004',
        actor: 'traveler',
        text: 'Landing complete. I will meet the receiver at the airport pickup lounge and send the final pin shortly.',
        sentAt: '2026-03-24T18:58:00.000Z',
      },
    ],
    checkpoints: [
      {
        id: 'thread-002-checkpoint-001',
        label: 'Pickup + seal check',
        location: 'Noida Sector 62',
        etaLabel: 'Completed at 8:20 AM',
        status: 'completed',
      },
      {
        id: 'thread-002-checkpoint-002',
        label: 'In-flight transfer',
        location: 'Kempegowda Airport transfer desk',
        etaLabel: 'Live now',
        status: 'active',
      },
      {
        id: 'thread-002-checkpoint-003',
        label: 'Receiver OTP handoff',
        location: 'Airport pickup lounge, Bengaluru',
        etaLabel: 'ETA 8:15 PM',
        status: 'upcoming',
      },
    ],
  },
];

export const seedAssignmentNotifications: AssignmentNotification[] = [];
